# Generated by Django 5.0.4 on 2024-04-28 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("start_price", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name="listing",
            name="product",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="listing",
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="timestamp",
            new_name="bid_time",
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="bidder",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="price",
        ),
        migrations.AddField(
            model_name="bid",
            name="bid_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "replies",
                    models.ManyToManyField(
                        related_name="reply_to", to="auction.comment"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="auction.item",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bid",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auction.item",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Listing",
        ),
    ]
